services:
  crypto-terminal:
    build: .
    container_name: crypto-terminal
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - telegram-bot

  telegram-bot:
    build: ./telegram-bot
    container_name: telegram-bot
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ./telegram-bot:/app
      - ./schemas:/schemas:ro
    restart: unless-stopped
