export const ALL_TIMEFRAMES = ["1m", "3m", "5m", "15m", "1h", "4h", "1d", "1w", "1M"] as const;
export const ALL_SESSIONS = ["London", "US", "Asia"] as const;

export const ALERT_CATEGORY_IDS = [
    'atr_expand',
    'context_summary',
    'ema_cross',
    'extreme_funding',
    'level_testing',
    'liquidation',
    'market_context',
    'oi_spike',
    'order_flow',
    'rsi_extreme',
    'rvol_spike',
    'whale',
    'macd_cross',
    'bb_squeeze',
    'bb_breakout',
    'stoch_extreme',
    'oi_divergence',
] as const;

export const TIMEFRAME_SUPPORTED_CATEGORIES = [
    'atr_expand',
    'context_summary',
    'ema_cross',
    'level_testing',
    'oi_spike',
    'order_flow',
    'rsi_extreme',
    'rvol_spike',
    'macd_cross',
    'bb_squeeze',
    'bb_breakout',
    'stoch_extreme',
    'oi_divergence',
] as const;

export const ALERT_THRESHOLD_IDS = [
    'atrExpansionRatio',
    'emaSeparationPct',
    'fundingExtremeRate',
    'liquidationMinAmount',
    'oiSpikePercentage',
    'rsiOverbought',
    'rsiOversold',
    'rvolMultiplier',
    'whaleMomentumDelta',
    'whaleMinAmount',
    'macdFreshnessRatio',
    'bbSqueezeWidthPct',
    'stochOverbought',
    'stochOversold',
    'oiDivergenceLookbackBars',
] as const;

export const HELP_CONTENT: Record<string, string> = {
    atr_expand: 'Uses ATR Ratio to detect when price ranges are expanding rapidly (high risk) or contracting (breakout potential).',
    context_summary: 'A state analyzer that alerts only when the combined Regime, Flow, and Volatility states shift.',
    ema_cross: 'Identifies Trend vs. Range conditions based on EMA 21/50 crossovers and price positioning.',
    extreme_funding: 'Alerts on unbalanced leverage. Extremely high/low rates increase the risk of cascading squeeze events.',
    level_testing: 'Detects when price interacts with high-volume nodes like POC or technical anchors like VWAP.',
    liquidation: 'Alerts on forced order closures. High clusters of liquidations often mark local price exhaustion.',
    market_context: 'Periodic (4h) and Daily (24h) summaries of overall market health and cumulative flows.',
    oi_spike: 'Monitors sudden leverage changes. Spikes suggest new aggressive positioning; Flushes suggest liquidations or mass profit-taking.',
    order_flow: 'Combines Price and OI delta to identify Active Long Building vs Short Covering dynamics.',
    rsi_extreme: 'Signals overbought (>70) or oversold (<30) conditions where momentum may be exhausted.',
    rvol_spike: 'Alerts when volume is significantly higher than the 20-period average, indicating high conviction.',
    whale: 'Tracks large individual orders and net flows. Can signal localized support/resistance or institutional aggression.',
    macd_cross: 'Triggers on fresh MACD signal-line crosses when the histogram is still near zero and momentum is just turning.',
    bb_squeeze: 'Detects Bollinger Band compression when width drops below the configured squeeze threshold.',
    bb_breakout: 'Alerts when price closes outside the upper or lower Bollinger Band after volatility expands.',
    stoch_extreme: 'Flags StochRSI overbought and oversold extremes based on configurable K-thresholds and crossover direction.',
    oi_divergence: 'Detects bearish or bullish divergence when recent OI direction disagrees with price trend over the configured lookback.',
    atrExpansionRatio: 'The ratio of current candle range vs average range. 1.3x indicates significant volatility expansion.',
    emaSeparationPct: 'The percentage gap between EMA 21 and 50 required to classify a trend as "Strong."',
    fundingExtremeRate: 'The percentage rate at which funding is considered unbalanced (e.g., 0.05% per 8h).',
    liquidationMinAmount: 'The minimum dollar volume of a forced order to trigger a Liquidation notification.',
    oiSpikePercentage: 'The percentage change in Open Interest over a 5-minute rolling window required for an alert.',
    rsiOverbought: 'The RSI level above which the market is considered over-extended and vulnerable to a pullback.',
    rsiOversold: 'The RSI level below which the market is considered oversold and potential for a relief bounce.',
    whaleMinAmount: 'The minimum dollar volume required to trigger a individual Whale Trade notification.',
    whaleMomentumDelta: 'The net aggression floor ($) required to trigger a Whale Momentum Shift alert.',
    macdFreshnessRatio: 'How close the MACD histogram must be to zero, relative to MACD value, for a cross to count as fresh.',
    bbSqueezeWidthPct: 'The Bollinger Band width percentage below which the market is considered compressed.',
    stochOverbought: 'The StochRSI K threshold above which momentum is considered overbought.',
    stochOversold: 'The StochRSI K threshold below which momentum is considered oversold.',
    oiDivergenceLookbackBars: 'The number of recent OI samples compared when checking price-versus-open-interest divergence.',
};
